### PR TITLE
add bokeh balls 002

### PR DESCRIPTION
**Pull request by xh3b4sd**
I found https://codepen.io/owlypixel/pen/bqBvRe and wanted to try it out but pretty quickly ran into a wall. Running `go run main.go` and visiting http://localhost:8000/backgrounds/bokehballs.002.html does not fully look like in Codepen and it also does not move. 

Screenshot 2020-05-08 at 21 39 47

### CODE REVIEW

**Comment by oponder** [comment]
When you copy the CSS from codepen, make sure to get real CSS and not SCSS or any other preprocessed CSS language.

Click "View compiled CSS" and copy the result, I think that might fix the problem.

Screenshot 2020-05-11 at 3 44 17 PM

**Comment by xh3b4sd** [comment]
Thanks for the hint. When I tried that out my shitty Atom just crashed because it is not good with such an amount of code editing at once.

**Comment by oponder** [comment]
Heh yeah this effect seems to require quite a few lines of css :P That editor doesn't sound so great though.

**Comment by oponder** [comment]
Do we still wanna get this effect in ? I can help with making it work if you want.

**Comment by xh3b4sd** [comment]
When you feel like it please go for it. I do not plan to do much here for now. We initiated the project and now I would like to see some organic traction before more doing on my own. I am also quite busy now with my Team Firecracker work and others.

**Comment by oponder** [comment]
Got them working. Will commit it in case anyone wants to use it as a bg in a future story.

**Pull request merged**
