### PR TITLE
Add sounds

### PR DESCRIPTION
**Pull request by oponder**
Adds some sound effects because.. why not? /shrug

Lets the user know the slide is advancing, and also if they reached the end.

### CODE REVIEW

**Comment by xh3b4sd** [comment]
For me personally I hate it when sites have sound effects. Especially when I do not know how to mute it. I probably enjoy music while checking out this site and then wonder where the noise is coming from. When you play videos and have the option to play their sound this makes more sense as you kind of opt in but getting forced to consume certain media types makes me leave websites immediately.

**Comment by oponder** [comment]
yeah it's very subtle though, have you tried it? Im not super opinionated about it, but i thought it was a cute extra touch.

**Comment by xh3b4sd** [comment]
Didn't even try. 🙈

**Comment by oponder** [comment]
I think I will add it as an easter egg that you can enable by pressing some other key first :P

I like it, but I can see how having it on by default is not great.

**Comment by xh3b4sd** [comment]
Poweruser feature makes sense.

**Comment by oponder** [comment]
Merging to reduce the number of open PR's on my mind.

Sounds have been disabled by default. When we pick this up again, I can make some interface element or shortcut key that allows people that want sounds to turn them on again.

**Pull request merged**
